### ISSUE TITLE
pep8 and pvlib standards

### ISSUE THREAD

**Issue by wholmgren** [MoonRaker/pvlib-python#10]
There are a couple of pep8 issues. The most important ones to me are:
- no camelCase. `forecast.py` offenders: `calcWind, addRadiation`
- spaces after commas, between comparators (`<`), between operators (`+`)
- line length should be less than 80 lines.
- lowercase parameter names e.g. `Half --> half, Quarter --> quarter`.

Here is the link to the pvlib variable name guide:

https://github.com/pvlib/pvlib-python/wiki/Variables-and-style-rules

For consistency with the rest of pvlib, I'd like to use:
1. `latitude` and `longitude` instead of `latlon`
2. `ghi` instead of `downward_shortwave_radflux`
3. `dni_extra` instead of `sp0`.

**Comment by MoonRaker** [comment]
All of these issues I have addressed. Unless you see any other issues I am considering this done for now.
