### ISSUE TITLE
test_forecast

### ISSUE THREAD

**Issue by wholmgren** [MoonRaker/pvlib-python#12]
Some notes on `test_forecast.py`...
- [ ] `test_fmcreation` has a clever `inspect.getmembers(forecast,inspect.isclass)` call. Might be a little too clever? Not sure what the advantage of the `_model_list` of strings is over a list of classes.
- [ ] `test_data_query`: why are we allowing the exception? In case a model is not available? Maybe just a comment is needed.
- [ ] `test_vert_level`: while not a problem to have here, I'm just wondering what the use of this is.

**Comment by wholmgren** [comment]
Comprehensive tests are a high priority!

**Comment by MoonRaker** [comment]
Yes, it should have been... now it is.

**Comment by MoonRaker** [comment]
All tests are now written and covers all the code. This includes the latest and hopefully most of the main updates at least for now.
