### ISSUE TITLE
remove ``location`` from get_query_data

### ISSUE THREAD

**Issue by wholmgren** [MoonRaker/pvlib-python#16]
It's unfortunate that the current state of pvlib requires people to use location objects for some functions. I'd rather hack around this problem internally than introduce more functions that use this soon-to-be-removed design pattern (see pvlib/pvlib-python#93). I think that all we need to do is set

``` python
self.location = pvlib.location.Location(latitude, longitude)
```

and everything should work.

**Comment by MoonRaker** [comment]
I was mainly using the location as a way of handling the time zone which meant the timezone of the location and time had to agree. I will make it internal and make sure that the time zones agree.
