### ISSUE TITLE
HRRR_ESRL does not work

### ISSUE THREAD

**Issue by wholmgren** [MoonRaker/pvlib-python#18]
I get the following error

``` python
HTTPError: 404 Client Error: Not Found for url: http://thredds-jumbo.unidata.ucar.edu/thredds/catalog/grib/HRRR/CONUS_3km/surface/catalog.xml
```

I looked at the thredds server and it seems that the data is missing. So, maybe not a problem with our code, but I wanted to flag it anyways.

**Comment by MoonRaker** [comment]
That is because there is hasn't been any data available on the THREDDS server for that model for several weeks. I am not sure why. I have added a try except block to the code that gives a warning about this.
