### ISSUE TITLE
test_forecasting.py

### ISSUE THREAD

**Issue by wholmgren** [MoonRaker/pvlib-python#2]
We need a `pvlib/test/test_forecasting.py` module that performs automated tests of `forecasting.py`.

**Comment by wholmgren** [comment]
Also, what's your plan for `pvlib/forecast_testing.py`? It seems to me that it might be the start of both the automated testing and a documentation page with inline figures, but it the file itself needs to go since it doesn't fit in the structure.

**Comment by MoonRaker** [comment]
That sounds good. I left it in because I hadn't decided which direction to go but I think we covered this in Issue #3.

**Comment by MoonRaker** [comment]
I have converted the forecast_testing.py file to an jupyter/ipython notebook and also created scripts for from all of the notebooks as well.

**Comment by wholmgren** [comment]
We still need a module in `pvlib/test` that is named `test_forecasting.py` that performs automated unit tests of `forecasting.py` and that can be run by `nose`, just the same as every other module in pvlib. The notebooks are not the same thing as unit tests. Maybe look at the other modules in `pvlib/test` as an example.

I will need to review the converted scripts in more detail before I can comment on whether or not I think that's something that we should integrate into the documentation. One thing that I can say now though is that I don't think that we should ask people to create custom profiles just so that they can run the notebooks since that's not user friendly.

**Comment by MoonRaker** [comment]
I will work on the automated test script for forecast.py.

What do you mean by custom profiles?

**Comment by MoonRaker** [comment]
This file longer exists and has been split into several Jupyter/Ipython notebooks.
