### ISSUE TITLE
documentation and/or tutorial

### ISSUE THREAD

**Issue by wholmgren** [MoonRaker/pvlib-python#3]
Sometimes I like our IPython Notebook tutorials and sometimes I think we need to have more traditional documentation beyond just the API. Your perspective would be very helpful here. What do you want to write for forecasting? Traditional docs or an IPython Notebook?

**Comment by MoonRaker** [comment]
I thought about this as well. It is easy enough to do both. I think the utility of just being able to grab a traditional module and run with and begin making it my own. However, the Ipython notebooks are useful for those who are less familiar with programming or the library and want to see how and if it will work for them. It also gives a bit more detail as to why things are the way there in the code. This seems especially useful when problems or challenges arise with using the library. For now I will construct both and see how they are received.

**Comment by MoonRaker** [comment]
I have updated and verified that both the forecast.ipynb and the forecast_to_power.ipynb work as they should with the most recent commits. Do you think that these notebooks are sufficient or are they missing functionality of the models that we should include yet?

**Comment by wholmgren** [comment]
It would be great if we could get some of the overview material in your powerpoint into the sphinx documentation. This would be separate from the API documentation and it would live in [`docs/sphinx/source`](https://github.com/MoonRaker/pvlib-python/tree/master/docs/sphinx/source).

I'm sure that you're aware of some of this, but here are comments on each notebook...

`forecast.ipynb`:
- [x] Don't use wildcard imports such as `from pvlib.forecast import *`
- [x] No need to make lat/lon a list
- [x] I recommend making use of pandas' plot function instead of using `plot_dates` e.g.
  
  ``` python
  ax = data['temperature'].plot()
  ax.set_ylabel('{} ({})'.format(fm.var_stdnames[var_name], fm.var_units[var_name]))
  ax.set_xlabel('Forecast Time ({})'.format(data.index.tz))
  ```
  
  and
  
  ``` python
  data[cloud_vars].plot()
  ```
  
  etc. If you continue to use `time_values` it should be referenced to `data.index` instead `fm.time`.
- [x] Fix UTC label problems with some models.
- [x] Add a title, introduction, and some notes. See the original [solar testing tutorial](http://nbviewer.ipython.org/github/wholmgren/siphon/blob/solar_testing/examples/notebooks/solar_testing.ipynb) for reference.

`forecast_to_power.ipynb`:
- [x] there are some cells that are formatted as "raw nbconvert" instead of "markdown"
- [x] lat/lon list issue.
- [x] get rid of everything from cell 35 onward (the scatter plots, etc.)

**Comment by MoonRaker** [comment]
All these fixes have been made and both notebooks have been run in full.
